name: Conventional Commits
permissions: {}

on:
  pull_request:
    branches: ["main", "release-*"]
  merge_group:

concurrency:
  group: commit-lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  commits:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: ["20"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: ${{ matrix.node }}
      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Verify conventional commits
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
